main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: 1Rogue
website: http://codelanx.com/
commands:
  voxelregen:
    aliases: [vr]